"""Disk-backed image storage with metadata index (stdlib-only).

Provides durable persistence for images generated by aigpt-api so that history
cards, thumbnails, and follow-up edits survive server restarts without pulling
in vendor heavyweight dependencies (PIL, FastAPI, curl_cffi).

Storage architecture:
- Images stored under `_IMAGES_ROOT/<YYYY>/<MM>/<DD>/<ts>_<id><ext>`
- Index stored in `_INDEX_FILE` as a JSON map of item records keyed by file id
- Keeps up to `_INDEX_MAX` (100) most recent images, evicting oldest on disk & index
- Path traversal guarded; self-healing cleanup on disk drift (missing files)
"""
from __future__ import annotations

import json
import os
from datetime import datetime
from pathlib import Path
import secrets
import shutil
import threading
from typing import Any

_IMAGES_ROOT = Path(__file__).resolve().parent / "_vendor" / "data" / "images"
_INDEX_FILE = Path(__file__).resolve().parent / "_vendor" / "data" / "images_index.json"
_INDEX_LOCK = threading.Lock()
_INDEX_MAX = 100
_IMAGE_EXT = {".png", ".jpg", ".jpeg", ".webp"}


def _load_index() -> dict[str, Any]:
    """Read the index file safely. Returns an index dict with an 'items' mapping."""
    if not _INDEX_FILE.exists():
        return {"items": {}}
    try:
        data = json.loads(_INDEX_FILE.read_text(encoding="utf-8"))
        if isinstance(data, dict):
            if not isinstance(data.get("items"), dict):
                data["items"] = {}
            return data
    except Exception:
        pass
    return {"items": {}}


def _save_index(data: dict[str, Any]) -> None:
    """Atomically write index dict using a temporary file and rename."""
    _INDEX_FILE.parent.mkdir(parents=True, exist_ok=True)
    tmp_file = _INDEX_FILE.with_suffix(_INDEX_FILE.suffix + f".tmp.{secrets.token_hex(4)}")
    tmp_file.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    tmp_file.replace(_INDEX_FILE)


def _guard_rel(rel: str | None) -> Path | None:
    """Validate relative path to prevent directory traversal outside `_IMAGES_ROOT`."""
    if not rel or not isinstance(rel, str):
        return None
    val = rel.strip().replace("\\", "/").lstrip("/")
    if not val:
        return None
    parts = Path(val).parts
    if any(p in {"", ".", ".."} or p.endswith(":") for p in parts):
        return None
    root = _IMAGES_ROOT.resolve()
    try:
        target = (root / val).resolve()
        target.relative_to(root)
    except (ValueError, RuntimeError):
        return None
    if target == root:
        return None
    return target


def save(image_path: str | Path, conversation_id: str = "", file_id: str | None = None) -> str:
    """Copy an image into durable storage, update the index, and evict old entries.

    Returns the file_id string.
    """
    src = Path(image_path).resolve()
    assigned_id = file_id or secrets.token_hex(8)
    if not src.exists() or not src.is_file():
        return assigned_id

    now = datetime.now()
    date_str = now.strftime("%Y-%m-%d")
    created_at_str = now.strftime("%Y-%m-%d %H:%M:%S")
    ts = int(now.timestamp())
    ext = src.suffix.lower()
    if ext not in _IMAGE_EXT:
        ext = ".png"

    dest_dir = _IMAGES_ROOT / now.strftime("%Y") / now.strftime("%m") / now.strftime("%d")
    dest_dir.mkdir(parents=True, exist_ok=True)
    dest_name = f"{ts}_{assigned_id}{ext}"
    dest_path = dest_dir / dest_name

    try:
        shutil.copy2(src, dest_path)
    except OSError:
        return assigned_id

    rel_posix = dest_path.relative_to(_IMAGES_ROOT).as_posix()

    with _INDEX_LOCK:
        index = _load_index()
        items = index.get("items", {})
        items[assigned_id] = {
            "rel": rel_posix,
            "path": str(dest_path),
            "name": dest_name,
            "date": date_str,
            "created_at": created_at_str,
            "size": dest_path.stat().st_size if dest_path.exists() else 0,
            "storage": "local",
            "local": True,
            "webdav": False,
            "conversation_id": conversation_id or "",
        }

        # Evict oldest if exceeding _INDEX_MAX
        if len(items) > _INDEX_MAX:
            sorted_keys = sorted(items.keys(), key=lambda k: items[k].get("created_at", ""))
            while len(items) > _INDEX_MAX and sorted_keys:
                old_id = sorted_keys.pop(0)
                old_row = items.pop(old_id, None)
                if old_row:
                    old_path = _guard_rel(old_row.get("rel"))
                    if old_path and old_path.exists():
                        try:
                            old_path.unlink()
                        except OSError:
                            pass

        index["items"] = items
        _save_index(index)

    return assigned_id


def lookup(file_id: str) -> Path | None:
    """Look up a file by id in the index. Self-heals if the file was deleted from disk."""
    if not file_id:
        return None
    with _INDEX_LOCK:
        index = _load_index()
        items = index.get("items", {})
        row = items.get(file_id)
        if not row:
            return None
        rel = row.get("rel")
        path = _guard_rel(rel)
        if path is None or not path.exists() or not path.is_file():
            items.pop(file_id, None)
            index["items"] = items
            _save_index(index)
            return None
        return path


def list_items() -> list[dict[str, Any]]:
    """Return all indexed image items sorted by created_at descending."""
    with _INDEX_LOCK:
        index = _load_index()
        items = index.get("items", {})
        res: list[dict[str, Any]] = []
        for fid, row in items.items():
            entry = dict(row)
            entry["id"] = fid
            res.append(entry)
        res.sort(key=lambda x: x.get("created_at", ""), reverse=True)
        return res


def delete(file_id: str) -> None:
    """Remove an item from index and delete the file from disk."""
    if not file_id:
        return
    with _INDEX_LOCK:
        index = _load_index()
        items = index.get("items", {})
        if file_id in items:
            row = items.pop(file_id)
            path = _guard_rel(row.get("rel"))
            if path and path.exists():
                try:
                    path.unlink()
                except OSError:
                    pass
            index["items"] = items
            _save_index(index)
